config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  devise_for :users
  get 'homes/index'
  root to: "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/submission.rb
class Submission < ApplicationRecord
  mount_uploader :submission_image, SubmissionImageUploader
  mount_uploader :submission_video, SubmissionVideoUploader

  belongs_to :user
  
  validates :title, presence: true
  validates :body, length: { maximum: 8000 }
  validates :url, url: true, allow_blank: true 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_many :submissions        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @submissions = Submission.all
  end


  def show
  end

  def new
    @submission = current_user.submissions.build
  end

  def edit
  end


  def create
    @submission = current_user.submissions.build(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_submission
      @submission = Submission.find(params[:id])
    end


    def submission_params
      params.require(:submission).permit(:title, :body, :url, :submission_image, :submission_video )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_svg(name, styles: "fill-current text-gray-400", title: nil)
    filename = "#{name}.svg"
    title ||= name.underscore.humanize
    inline_svg(filename, aria: true, nocomment: true, title: title, class: styles)
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/homes/index.html.erb
<div class="container m-auto">
  <h1 class="font-mono mb-4 text-red-400 ">Home</h1>
  <p class="text-m">Find me in app</p>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webbit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=IBM+Plex+Sans:400,400i,500,600,700'%>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gray-200 relative h-screen overflow-x-hidden">
    <% flash.each do |type, message| %>
      <% if type == "alert" %>
        <div class="bg-red-500">
          <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans">
            <%= message %>
          </div>
        </div>
      <% end %>

      <% if type == "notice" %>
        <div class="bg-red-500">
          <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans">
            <%= message %>
          </div>
        </div>
      <% end %>
    <% end %>

    <nav class="bg-white py-2 border-b border-gray-400" role="navigation" aria-label="main navigation">
      <div class="flex flex-wrap items-center justify-center lg:justify-start lg:content-center px-4 lg:px-6">
        <%= link_to root_path, class: "leading-normal no-underline text-gray-800 my-2 md:my-0" do %>
          <h1 class="text-lg pr-2 font-bold">WEBBIT</h1>
        <% end %>

        <div class="flex flex-wrap justify-start w-full lg:w-2/3">
          <div class="w-full lg:w-1/4 px-0 md:px-2 mb-2 lg:mb-0">
            <div class="relative">
              <select  id="community" class="select">
                <option>Community 1</option>
                <option>Community 2</option>
                <option>Community 3</option>
              </select>
              <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-black-700">
                <%= render_svg 'icons/chevron-down' %>
              </div>
            </div>
          </div>
        </div>

        <div class="w-full lg:w-1/2 px-0 md:px-2">
          <div class="relative">
            <input type="text" class="input pl-10" placeholder="Search Webbit">
            <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-600">
              <svg class="fill-current h-4 w-4" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>search</title><path d="M22.414 19.586l-4.801-4.801A8.942 8.942 0 0 0 19 10a9 9 0 1 0-9 9 8.942 8.942 0 0 0 4.785-1.387l4.801 4.801c.39.391.902.586 1.414.586s1.024-.195 1.414-.586a2 2 0 0 0 0-2.828zM10 15c-2.757 0-5-2.243-5-5s2.243-5 5-5 5 2.243 5 5-2.243 5-5 5z" /></svg>
            </div>
          </div>
        </div>

        <div class="w-full flex flex-wrap flex-1 items-center justify-end pt-4 lg:pt-0">
          <div class="mr-3">

              <% if user_signed_in? %>
                <%= link_to new_submission_path do %>
                  <%= render_svg 'icons/create' %>
                <% end %>
              <% else %>
                <%= link_to "Login", new_user_session_path, class: 'btn btn-outline btn-small mr-2' %>
                <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-outline btn-small mr-2' %>
              <% end %>

              <% if user_signed_in? %>
                <div class="dropdown rounded bg-white border border-gray-400 text-gray-600 ml-1 hover:bg-gray-200">
                  <div class="dropdown-content pt-2 pb-2 pl-3 pr-1">
                    <%= link_to "#", class: "js-dropdown-user-target no-underline flex justify-between text-gray-700 uppercase text-xs tracking-wide items-center font-semibold" do %>
                      <%= current_user.username if current_user.username %>
                      <%= render_svg "icons/chevron-down" %>
                    <% end %>

                    <ul class="list-none hidden dropdown-list absolute left-0 rounded-b border border-gray-500 shadow">
                      <h5 class="mt-2 uppercase text-xs text-gray-500 font-normal py-2 pl-3 tracking-wide">My Stuff</h5>
                      <li>
                        <%= link_to "#", class: "hover:bg-purple-500 hover:text-white text-gray-700 no-underline block py-2 px-4 flex items-center text-sm" do %> 
                          <%= render_svg "icons/user", style: "icon-md fill-current text-gray-600 mr-3" %> My Profile
                        <% end %>
                      </li>

                      <li>
                        <%= link_to edit_user_regirstration_path, class: "hover:bg-purple-500 hover:text-white text-gray-700 no-underline block py-2 px-4 flex items-center text-sm" do %> 
                          <%= render_svg "icons/settings", style: "icon-md fill-current text-gray-600 mr-3" %> Account Settings 
                        <% end %>
                      </li>

                      <li>
                        <%= link_to destroy_user_session_path, class: "hover:bg-purple-500 hover:text-white text-gray-700 no-underline block py-2 px-4 flex items-center text-sm" do %> 
                          <%= render_svg "icons/settings", style: "icon-md fill-current text-gray-600 mr-3" %> Sign Out
                        <% end %>
                      </li>
                    </ul>



                  </div>
                </div>
              <% end %>
          </div>

        </div>
    </nav>

    

    <%= link_to "Sign Out", destroy_user_session_path, method: :delete%>

    <%= yield %>
  </body>
</html>

app/views/submissions/_form.html.erb
<%= form_with(model: submission, local: true) do |form| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
        <% submission.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :submission_image %>
    <%= form.file_field :submission_image %>
  </div>

  <div class="field">
    <%= form.label :submission_video %>
    <%= form.file_field :submission_video %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<h1>Submissions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.title %></td>
        <td><%= submission.body %></td>
        <td><%= submission.url %></td>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @submission.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @submission.body %>
</p>

<p>
  <strong>Url:</strong>
  <%= @submission.url %>
</p>

<p>
  <strong>Submission Image:</strong>
  <%= image_tag @submission.submission_image.large.url, width: 400 %>
</p>

<%# <p>
  <strong>Submission Video</strong>
  
</p> %>

<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>